---
- name: Pull running config from SRX1500
  hosts: 10.254.16.8
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: junos
    ansible_user: junadmin
    ansible_password: 20lancer
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Retrieve the running configuration
      junipernetworks.junos.junos_command:
        commands: "show configuration"
      register: running_config

    - name: Save the configuration to a file
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "srx1500_running_config.txt"
