---
- name: Retrieve Active Configuration from Juniper SRX1500
  hosts: juniper_firewalls
  gather_facts: no
  connection: local  # Use local connection to interact with the Junos device

  tasks:
    - name: Collect the current configuration from the Juniper SRX1500
      junipernetworks.junos:
        provider:
          host: "10.254.16.8"
          username: "junadmin"
          password: "20lancer"
          port: 22
        format: text
        retrieve: committed
      register: junos_config

    - name: Save the configuration to a local file
      copy:
        content: "{{ junos_config.stdout }}"
        dest: "./configs/{{ inventory_hostname }}_config.txt"
