---
- name: "Get Junos OS configuration"
  hosts: junos-all
  connection: local
  gather_facts: no

  tasks:
    - name: "Get candidate configuration"
      juniper.device.config:
        retrieve: "candidate"
      register: response
    - name: "Print result"
      debug:
        var: response
