- name: Ping host 10.254.17.10
  hosts: webstack
  connection: ssh

  tasks:
    - name: Ping the target host
      ping:
        host: webstack
        count: 1000
        interval: 1

  vars:
    webstack:
      ansible_host: webstack
