- name: Ping host 10.254.17.10
  #hosts: 10.254.17.10
  hosts: localhost
  connection: ssh

  tasks:
    - name: Ping the target host
      ansible.builtin.ping:
      register: ping_result
        
    - name: Show ping result
      ansible.builtin.debug:
        msg: "Ping response: {{ ping_result }}"

  

    

  #vars:
    #pingstack:
      #ansible_host: 10.254.17.10
